/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    houses: House;
    products: Product;
    carts: Cart;
    orders: Order;
    'jenis-batik': JenisBatik;
    'jenis-kain': JenisKain;
    'jenis-produk': JenisProduk;
    'payment-proofs': PaymentProof;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    houses: HousesSelect<false> | HousesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'jenis-batik': JenisBatikSelect<false> | JenisBatikSelect<true>;
    'jenis-kain': JenisKainSelect<false> | JenisKainSelect<true>;
    'jenis-produk': JenisProdukSelect<false> | JenisProdukSelect<true>;
    'payment-proofs': PaymentProofsSelect<false> | PaymentProofsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'home-page': HomePage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'customer' | 'store-admin')[];
  house?: (number | null) | House;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Rumah adalah lini merek atau nama toko.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "houses".
 */
export interface House {
  id: number;
  name: string;
  slug?: string | null;
  logo?: (number | null) | Media;
  description?: string | null;
  phoneNumber: string;
  availableBatikTypes: (number | JenisBatik)[];
  availableFabricTypes: (number | JenisKain)[];
  socialMedia?: {
    instagramUrl?: string | null;
    tiktokUrl?: string | null;
  };
  marketplaces?: {
    shopeeUrl?: string | null;
    tokopediaUrl?: string | null;
  };
  /**
   * Rekening ini akan ditampilkan kepada pelanggan untuk melakukan pembayaran.
   */
  bankDetails: {
    bankName: string;
    accountNumber: string;
    accountHolderName: string;
  };
  /**
   * Dapatkan ID Kota dari dokumentasi RajaOngkir. Contact Developer untuk mendapatkan ID daerah jika produk tidak dikirim dari desa pungsari.
   */
  originCity: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Jenis atau teknik pembuatan batik (misal: Tulis, Cap, Printing).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jenis-batik".
 */
export interface JenisBatik {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Jenis kain yang digunakan untuk batik (misal: Katun, Sutra).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jenis-kain".
 */
export interface JenisKain {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Produk batik yang akan dijual di situs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug?: string | null;
  house: number | House;
  /**
   * Masukkan harga dalam Rupiah.
   */
  price: number;
  description: string;
  /**
   * Tambahkan detail penting seperti Bahan, Asal, Petunjuk Perawatan, dll.
   */
  details?:
    | {
        detailItem: string;
        id?: string | null;
      }[]
    | null;
  jenisBatik: (number | JenisBatik)[];
  jenisKain: (number | JenisKain)[];
  jenisProduk?: (number | null) | JenisProduk;
  /**
   * (Opsional) Tambahkan link jika produk ini dijual di marketplace
   */
  marketplaceLinks?: {
    shopeeUrl?: string | null;
    tokopediaUrl?: string | null;
    tiktokUrl?: string | null;
  };
  /**
   * Masukkan berat produk dalam satuan gram. Akan digunakan saat menghitung ongkir.
   */
  weight: number;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Jenis produk batik (misal: Kain, Kemeja, Celana, Tas, dsb).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jenis-produk".
 */
export interface JenisProduk {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Users' shopping carts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  user: number | User;
  items?:
    | {
        product: number | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A collection to store customer orders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  user?: (number | null) | User;
  customerEmail: string;
  subtotal: number;
  total: number;
  status: 'pending' | 'processing' | 'shipped' | 'completed' | 'cancelled';
  proof_of_payment?: (number | null) | PaymentProof;
  trackingNumber?: string | null;
  house: number | House;
  items: {
    product?: (number | null) | Product;
    productName: string;
    price: number;
    quantity: number;
    id?: string | null;
  }[];
  shippingDetails: {
    service: string;
    cost: number;
  };
  shippingAddress: {
    recipientName: string;
    phoneNumber: string;
    fullAddress: string;
    postalCode: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-proofs".
 */
export interface PaymentProof {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'houses';
        value: number | House;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'jenis-batik';
        value: number | JenisBatik;
      } | null)
    | ({
        relationTo: 'jenis-kain';
        value: number | JenisKain;
      } | null)
    | ({
        relationTo: 'jenis-produk';
        value: number | JenisProduk;
      } | null)
    | ({
        relationTo: 'payment-proofs';
        value: number | PaymentProof;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  house?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "houses_select".
 */
export interface HousesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  phoneNumber?: T;
  availableBatikTypes?: T;
  availableFabricTypes?: T;
  socialMedia?:
    | T
    | {
        instagramUrl?: T;
        tiktokUrl?: T;
      };
  marketplaces?:
    | T
    | {
        shopeeUrl?: T;
        tokopediaUrl?: T;
      };
  bankDetails?:
    | T
    | {
        bankName?: T;
        accountNumber?: T;
        accountHolderName?: T;
      };
  originCity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  house?: T;
  price?: T;
  description?: T;
  details?:
    | T
    | {
        detailItem?: T;
        id?: T;
      };
  jenisBatik?: T;
  jenisKain?: T;
  jenisProduk?: T;
  marketplaceLinks?:
    | T
    | {
        shopeeUrl?: T;
        tokopediaUrl?: T;
        tiktokUrl?: T;
      };
  weight?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  customerEmail?: T;
  subtotal?: T;
  total?: T;
  status?: T;
  proof_of_payment?: T;
  trackingNumber?: T;
  house?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        price?: T;
        quantity?: T;
        id?: T;
      };
  shippingDetails?:
    | T
    | {
        service?: T;
        cost?: T;
      };
  shippingAddress?:
    | T
    | {
        recipientName?: T;
        phoneNumber?: T;
        fullAddress?: T;
        postalCode?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jenis-batik_select".
 */
export interface JenisBatikSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jenis-kain_select".
 */
export interface JenisKainSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jenis-produk_select".
 */
export interface JenisProdukSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-proofs_select".
 */
export interface PaymentProofsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroSection: {
    title: string;
    subtitle: string;
    backgroundVideo: number | Media;
  };
  aboutSection: {
    title: string;
    paragraph: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image: number | Media;
  };
  artisanSection: {
    title: string;
    subtitle: string;
    /**
     * Masukkan 5 data pengrajin yang akan ditampilkan di carousel halaman beranda.
     */
    featuredArtisans: {
      name: string;
      specialty: string;
      image: number | Media;
      description: string;
      id?: string | null;
    }[];
  };
  testimonialSection: {
    testimonials: {
      name: string;
      location?: string | null;
      rating: number;
      comment: string;
      id?: string | null;
    }[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundVideo?: T;
      };
  aboutSection?:
    | T
    | {
        title?: T;
        paragraph?: T;
        image?: T;
      };
  artisanSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        featuredArtisans?:
          | T
          | {
              name?: T;
              specialty?: T;
              image?: T;
              description?: T;
              id?: T;
            };
      };
  testimonialSection?:
    | T
    | {
        testimonials?:
          | T
          | {
              name?: T;
              location?: T;
              rating?: T;
              comment?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}